### PR TITLE
Add GSG sample for L475

### PR DESCRIPTION
**Pull request by ryanwinter**
## Purpose
Add the Getting Started Guide for the L475

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Follow instructions in demos/projects/ST/b-l475e-iot01a/GSG.md

### CODE REVIEW

**Comment by wduraes** [comment]
Could not make this work on a clean installed machine. Error:

C:\SRC\iot-middleware-freertos-samples>cmake --preset b-l475e-iot01a cmake --build --preset b-l475e-iot01a
CMake Error: Unknown argument --build
CMake Error: Run 'cmake --help' for all supported options.

C:\SRC\iot-middleware-freertos-samples>

**Comment by ryanwinter** [comment]
> Could not make this work on a clean installed machine. Error:
> 
> C:\SRC\iot-middleware-freertos-samples>cmake --preset b-l475e-iot01a cmake --build --preset b-l475e-iot01a
> CMake Error: Unknown argument --build
> CMake Error: Run 'cmake --help' for all supported options.
> 
> C:\SRC\iot-middleware-freertos-samples>



> Could not make this work on a clean installed machine. Error:
> 
> C:\SRC\iot-middleware-freertos-samples>cmake --preset b-l475e-iot01a cmake --build --preset b-l475e-iot01a
> CMake Error: Unknown argument --build
> CMake Error: Run 'cmake --help' for all supported options.
> 
> C:\SRC\iot-middleware-freertos-samples>

fixed formatting issue and added images.

**Comment by wduraes** [comment]
Sample built successfully, provision and connection works fine as well, but this sample is not getting a Device Template assigned. In the device list I see the device but it says "Unassigned". Because of that I can only get raw data from the device. Did I miss any step?

**Comment by wduraes** [comment]
The picture under "View Device Information" shows OS as "Azure RTOS" which shouldn't be the case.

**Comment by wduraes** [comment]
This GSG.md file is not linked anywhere, we should have it linked in the main readme file so that customers can find it.

**Comment by ryanwinter** [comment]
> Sample built successfully, provision and connection works fine as well, but this sample is not getting a Device Template assigned. In the device list I see the device but it says "Unassigned". Because of that I can only get raw data from the device. Did I miss any step?

There is a PR to add the new models to the model repository which we will need to accepted before this PR can be merged. 
https://github.com/Azure/iot-plugandplay-models/pull/346

**Review by wduraes — APPROVED** [review]

**Pull request merged**
